### ISSUE TITLE
Assignment 2 Complete

### ISSUE THREAD

**Issue by sivilyslare** [VIS-2129-F2020/cschmidt-vis#2]
https://vis-2129-f2020.github.io/cschmidt-vis/cschmidt-vis_assignment2.html

**Comment by bauranov** [comment]
Hi! Here are my comments:
- Add {r, warning=FALSE, message=FALSE} at the beginning of the code chunk to avoid all the messages and warnings in HTML.
- Add a space between hashtags and text to properly format a header (*## Map* instead of *##Map*).
- The assignment requirement was to try three different projections, choose one that makes the most sense and then plot the data. Sideways-US might not the most intuitive map, but hey, Florida finally gets to be on top.

Keep up the good work!
